name: ABCSMC
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython
  - matplotlib=3.5.2
  - numpy=1.22.4
  - pandas=1.4.3
  - python=3.8.13 
  - scipy=1.8.1
  - ipykernel=5.3.2
  - ipython=7.16.1
  - jupyter=1.0.0
  - notebook=6.0.3
  - numba=0.53.1
  - networkx=1.11
  - seaborn=0.13.2
